/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Manon
 */
public class DetailsPrestation extends javax.swing.JPanel {

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return NomPatient;
    }

    public JLabel getIPP() {
        return IPP;
    }

    public JLabel getNomMedecin() {
        return NomMedecin;
    }

    public JLabel getNomPatient() {
        return NomPatient;
    }

    public JLabel getPrenomPatient() {
        return PrenomPatient;
    }

    public JTextArea getDetails() {
        return details;
    }

   

    public JButton getEnvoyerResultat() {
        return envoyerResultat;
    }


    /**
     * @return the jLabelipp
     */
    public javax.swing.JLabel getjLabelipp() {
        return IPP;
    }

    /**
     * @return the jTextField1
     */
   

    public JButton getBoutonRetour() {
        return boutonRetour;
    }

    public JLabel getSrvice() {
        return Srvice;
    }

    public JLabel getDateDeDemande() {
        return dateDeDemande;
    }


   

    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return boutonRetour;
    }

    
    /**
     * Creates new form PrestationFaite
     */
    public DetailsPrestation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomPatient = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IPP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NomMedecin = new javax.swing.JLabel();
        PrenomPatient = new javax.swing.JLabel();
        envoyerResultat = new javax.swing.JButton();
        boutonRetour = new javax.swing.JButton();
        IPP1 = new javax.swing.JLabel();
        Srvice = new javax.swing.JLabel();
        dateDeDemande = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        details = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 10, true));

        NomPatient.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        NomPatient.setText("NOM");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/logo.png"))); // NOI18N

        IPP.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        IPP.setText("AAMMXXXXX");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setText("Détails :");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setText("Médecin prescripteur :");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel5.setText("Patient :");

        NomMedecin.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        NomMedecin.setText("NOM");

        PrenomPatient.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        PrenomPatient.setText("Prénom");

        envoyerResultat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        envoyerResultat.setText("Envoyer le Résultat");

        boutonRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/flcheretour-ConvertImage.png"))); // NOI18N

        IPP1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        IPP1.setText("Service Demandeur :");

        Srvice.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        Srvice.setText("NOM");

        dateDeDemande.setText("jLabel1");

        details.setColumns(20);
        details.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        details.setRows(5);
        jScrollPane1.setViewportView(details);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(envoyerResultat)
                        .addGap(681, 681, 681)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(boutonRetour))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(IPP1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(78, 78, 78)
                                        .addComponent(NomPatient)
                                        .addGap(55, 55, 55)
                                        .addComponent(PrenomPatient)
                                        .addGap(44, 44, 44)
                                        .addComponent(IPP)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NomMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(Srvice)
                                        .addGap(213, 213, 213)
                                        .addComponent(dateDeDemande))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addGap(0, 426, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boutonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomPatient)
                    .addComponent(IPP)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(NomMedecin)
                    .addComponent(PrenomPatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IPP1)
                    .addComponent(Srvice)
                    .addComponent(dateDeDemande))
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(envoyerResultat))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IPP;
    private javax.swing.JLabel IPP1;
    private javax.swing.JLabel NomMedecin;
    private javax.swing.JLabel NomPatient;
    private javax.swing.JLabel PrenomPatient;
    private javax.swing.JLabel Srvice;
    private javax.swing.JButton boutonRetour;
    private javax.swing.JLabel dateDeDemande;
    private javax.swing.JTextArea details;
    private javax.swing.JButton envoyerResultat;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
