/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.JLabel;

/**
 *
 * @author Manon
 */
public class DPIPH extends javax.swing.JPanel {

    /**
     * @return the dateentree
     */
    public javax.swing.JLabel getDateentree() {
        return dateentree;
    }

    /**
     * @param dateentree the dateentree to set
     */
    public void setDateentree(javax.swing.JLabel dateentree) {
        this.dateentree = dateentree;
    }

    /**
     * @return the datesortie
     */
    public javax.swing.JLabel getDatesortie() {
        return datesortie;
    }

    /**
     * @param datesortie the datesortie to set
     */
    public void setDatesortie(javax.swing.JLabel datesortie) {
        this.datesortie = datesortie;
    }

    /**
     * @return the etat
     */
    public javax.swing.JLabel getEtat() {
        return etat;
    }

    /**
     * @param etat the etat to set
     */
    public void setEtat(javax.swing.JLabel etat) {
        this.etat = etat;
    }

    /**
     * @return the typeDeSejour
     */
    public javax.swing.JLabel getTypeDeSejour() {
        return typeDeSejour;
    }

    /**
     * @return the jButton3
     */
    public javax.swing.JButton getjButton3() {
        return jButton3;
    }

    /**
     * @return the jButton1
     */
    
    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return jButton2;
    }

    /**
     * @return the jButtoninfomed
     */
    public javax.swing.JButton getjButtoninfomed() {
        return jButtoninfomed;
    }

    /**
     * @return the jButtonmodifier
     */
    

    /**
     * @return the jComboBox1
  
    /**
     * @return the jLabeladresse
     */
    public javax.swing.JLabel getjLabeladresse() {
        return jLabeladresse;
    }

    /**
     * @return the jLabelannée
     */
    public javax.swing.JLabel getjLabelannée() {
        return jLabelannée;
    }

    /**
     * @return the jLabelchamnre
     */
    public javax.swing.JLabel getjLabelchamnre() {
        return jLabelchamnre;
    }

    /**
     * @return the jLabelcodepostal
     */
   
    /**
     * @return the jLabelemail
     */
    public javax.swing.JLabel getjLabelemail() {
        return jLabelemail;
    }

    /**
     * @return the jLabelipp
     */
    public javax.swing.JLabel getjLabelipp() {
        return jLabelipp;
    }

    /**
     * @return the jLabelnom
     */
    public javax.swing.JLabel getjLabelnom() {
        return jLabelnom;
    }

    /**
     * @return the jLabelnumsecu
     */
    public javax.swing.JLabel getjLabelnumsecu() {
        return Sexe;
    }

    /**
     * @return the jLabelprenom
     */
    public javax.swing.JLabel getjLabelprenom() {
        return jLabelprenom;
    }

    /**
     * @return the jLabeltelephone
     */
    public javax.swing.JLabel getjLabeltelephone() {
        return jLabeltelephone;
    }

  
   

    public JLabel getjLabelnom1() {
        return jLabelnom1;
    }

    public JLabel getServiceGeo() {
        return ServiceGeo;
    }

    public JLabel getServiceRespo() {
        return ServiceRespo;
    }

    public JLabel getSexe() {
        return Sexe;
    }
    
    
    

    /**
     * Creates new form DPI
     */
    public DPIPH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabelprenom = new javax.swing.JLabel();
        jLabelnom = new javax.swing.JLabel();
        jLabelannée = new javax.swing.JLabel();
        Sexe = new javax.swing.JLabel();
        jLabelipp = new javax.swing.JLabel();
        jLabeladresse = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        jLabeltelephone = new javax.swing.JLabel();
        jButtoninfomed = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelchamnre = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabelnom1 = new javax.swing.JLabel();
        ServiceRespo = new javax.swing.JLabel();
        ServiceGeo = new javax.swing.JLabel();
        jLabelnumsecu1 = new javax.swing.JLabel();
        typeDeSejour = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dateentree = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        datesortie = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 10, true));
        setPreferredSize(new java.awt.Dimension(1700, 760));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/logo.png"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/flcheretour-ConvertImage.png"))); // NOI18N

        jLabelprenom.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jLabelprenom.setText("Prénom");

        jLabelnom.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jLabelnom.setText("NOM");

        jLabelannée.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabelannée.setText("AAAA");

        Sexe.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        Sexe.setText("Sexe");

        jLabelipp.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jLabelipp.setText("AAMMXXXXX");

        jLabeladresse.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabeladresse.setText("4 rue de la liberté");

        jLabelemail.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabelemail.setText("nom.prenom@email.com");

        jLabeltelephone.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabeltelephone.setText("0675984286");

        jButtoninfomed.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtoninfomed.setText("Accéder aux informations médicales");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel4.setText("Service responsable :");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel5.setText("Service géographique :");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel6.setText("Chambre :");

        jLabelchamnre.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabelchamnre.setText("XXX");

        jButton3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton3.setText("Transfert de service");

        jLabelnom1.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jLabelnom1.setText("NOM");

        ServiceRespo.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        ServiceRespo.setText("4 rue de la liberté");

        ServiceGeo.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        ServiceGeo.setText("4 rue de la liberté");

        jLabelnumsecu1.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabelnumsecu1.setText("2971162574323");

        typeDeSejour.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        typeDeSejour.setText("Type de séjour");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        jLabel2.setText("Etat :");

        etat.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        etat.setText("état");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        jLabel7.setText("Date d'entrée :");

        dateentree.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        dateentree.setText("Date d'entrée");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        jLabel8.setText("Date de sortie :");

        datesortie.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        datesortie.setText("Date de sortie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(415, 415, 415))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButtoninfomed)
                                        .addGap(335, 335, 335)))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabeladresse)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelnumsecu1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelannée, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Sexe))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(etat))
                                            .addComponent(typeDeSejour))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dateentree, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelnom)
                                                .addGap(135, 135, 135)
                                                .addComponent(jLabelnom1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                                        .addComponent(jLabelprenom)
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabelipp))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(datesortie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelemail)
                                    .addComponent(jLabeltelephone))))
                        .addGap(359, 359, 359)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ServiceGeo, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelchamnre)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ServiceRespo, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(283, 283, 283))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelnom)
                            .addComponent(jLabelprenom)
                            .addComponent(jLabelipp)
                            .addComponent(jLabelnom1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelannée)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sexe)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelnumsecu1)
                            .addComponent(jLabeladresse))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelemail)
                        .addGap(18, 18, 18)
                        .addComponent(jLabeltelephone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(ServiceRespo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(typeDeSejour)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(etat))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dateentree)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ServiceGeo)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabelchamnre)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(datesortie)
                        .addComponent(jLabel8)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtoninfomed)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ServiceGeo;
    private javax.swing.JLabel ServiceRespo;
    private javax.swing.JLabel Sexe;
    private javax.swing.JLabel dateentree;
    private javax.swing.JLabel datesortie;
    private javax.swing.JLabel etat;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtoninfomed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabeladresse;
    private javax.swing.JLabel jLabelannée;
    private javax.swing.JLabel jLabelchamnre;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelipp;
    private javax.swing.JLabel jLabelnom;
    private javax.swing.JLabel jLabelnom1;
    private javax.swing.JLabel jLabelnumsecu1;
    private javax.swing.JLabel jLabelprenom;
    private javax.swing.JLabel jLabeltelephone;
    private javax.swing.JLabel typeDeSejour;
    // End of variables declaration//GEN-END:variables
}
