/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.ConnexionBD;
import bd.MethodeBD;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Manon
 */
public class ListePersonnel extends javax.swing.JPanel {

    public JButton getAjouterPersonnel() {
        return AjouterPersonnel;
    }

    public JTextField getBarreDeRechercheIDE() {
        return BarreDeRechercheIDE;
    }

    public JTextField getBarreDeRechercheIDE1() {
        return BarreDeRechercheIDE1;
    }

    public JTextField getBarreDeRecherchePH() {
        return BarreDeRecherchePH;
    }

    public JTextField getBarreDeRecherchePersonnelMT() {
        return BarreDeRecherchePersonnelMT;
    }

    public JButton getBoutonIDE() {
        return BoutonIDE;
    }

    public JButton getBoutonRecherchePH() {
        return BoutonRecherchePH;
    }

    public JButton getBouttonMT() {
        return BouttonMT;
    }

    public JButton getBouttonMT1() {
        return BouttonMT1;
    }

    public JTable getTableIDE() {
        return TableIDE;
    }

    public JTable getTableMT() {
        return TableMT;
    }

    public JTable getTablePH() {
        return TablePH;
    }

    public JTable getTableSecretaire() {
        return TableSecretaire;
    }

    /**
     *
     *
     * /**
     * Creates new form InfosMedicales
     */
    public ListePersonnel() {
        initComponents();
        this.getTableIDE().setFont(new Font("Calibri", 0, 18));
        this.getTableIDE().setModel(new MethodeBD().listeIDE());
        this.getTablePH().setFont(new Font("Calibri", 0, 18));
        this.getTablePH().setModel(new MethodeBD().listePH());
        this.getTableMT().setFont(new Font("Calibri", 0, 18));
        this.getTableMT().setModel(new MethodeBD().listeMT());
        this.getTableSecretaire().setFont(new Font("Calibri", 0, 18));
        this.getTableSecretaire().setModel(new MethodeBD().listeSA());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AjouterPersonnel = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableIDE = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BarreDeRecherchePersonnelMT = new javax.swing.JTextField();
        BarreDeRecherchePH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BarreDeRechercheIDE = new javax.swing.JTextField();
        BoutonIDE = new javax.swing.JButton();
        BouttonMT = new javax.swing.JButton();
        BoutonRecherchePH = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablePH = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableSecretaire = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        TableMT = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        BarreDeRechercheIDE1 = new javax.swing.JTextField();
        BouttonMT1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 10, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/logo.png"))); // NOI18N

        AjouterPersonnel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        AjouterPersonnel.setText("Ajouter un personnel");

        TableIDE.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        TableIDE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom ", "Prénom ", "Service"
            }
        ));
        jScrollPane4.setViewportView(TableIDE);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Liste des Personnels Médico-techniques");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Liste des secretaires médicales :");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setText("Liste des Praticiens hospitaliers");

        BarreDeRecherchePersonnelMT.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BarreDeRecherchePersonnelMT.setText("Chercher Personnel MT  ...");
        BarreDeRecherchePersonnelMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarreDeRecherchePersonnelMTActionPerformed(evt);
            }
        });

        BarreDeRecherchePH.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BarreDeRecherchePH.setText("Chercher PH  ...");
        BarreDeRecherchePH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarreDeRecherchePHActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel3.setText("Liste du personnel de l'hopital Princeton Placeboro :");

        BarreDeRechercheIDE.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BarreDeRechercheIDE.setText("Chercher Secrétaire  ...");
        BarreDeRechercheIDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarreDeRechercheIDEActionPerformed(evt);
            }
        });

        BoutonIDE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/loupe.png"))); // NOI18N

        BouttonMT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/loupe.png"))); // NOI18N

        BoutonRecherchePH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/loupe.png"))); // NOI18N

        TablePH.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        TablePH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom ", "Prénom ", "Service"
            }
        ));
        jScrollPane5.setViewportView(TablePH);

        TableSecretaire.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        TableSecretaire.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom ", "Prénom ", "Service"
            }
        ));
        jScrollPane6.setViewportView(TableSecretaire);

        TableMT.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        TableMT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom ", "Prénom ", "Service"
            }
        ));
        jScrollPane7.setViewportView(TableMT);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setText("Liste de IDE");

        BarreDeRechercheIDE1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BarreDeRechercheIDE1.setText("Chercher IDE  ...");
        BarreDeRechercheIDE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarreDeRechercheIDE1ActionPerformed(evt);
            }
        });

        BouttonMT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/loupe.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AjouterPersonnel)
                                    .addGap(367, 367, 367)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(448, 448, 448)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7)
                                            .addGap(172, 172, 172)
                                            .addComponent(jLabel2)))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(48, 48, 48)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BarreDeRecherchePH, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BoutonRecherchePH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(BarreDeRechercheIDE1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BoutonIDE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(114, 114, 114)
                                        .addComponent(BarreDeRecherchePersonnelMT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BouttonMT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92)
                                        .addComponent(BarreDeRechercheIDE, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BouttonMT1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BarreDeRechercheIDE1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BoutonIDE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BouttonMT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BarreDeRecherchePersonnelMT, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BarreDeRechercheIDE))
                    .addComponent(BarreDeRecherchePH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoutonRecherchePH)
                    .addComponent(BouttonMT1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addComponent(AjouterPersonnel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BarreDeRecherchePersonnelMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarreDeRecherchePersonnelMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarreDeRecherchePersonnelMTActionPerformed

    private void BarreDeRecherchePHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarreDeRecherchePHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarreDeRecherchePHActionPerformed

    private void BarreDeRechercheIDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarreDeRechercheIDEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarreDeRechercheIDEActionPerformed

    private void BarreDeRechercheIDE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarreDeRechercheIDE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarreDeRechercheIDE1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterPersonnel;
    private javax.swing.JTextField BarreDeRechercheIDE;
    private javax.swing.JTextField BarreDeRechercheIDE1;
    private javax.swing.JTextField BarreDeRecherchePH;
    private javax.swing.JTextField BarreDeRecherchePersonnelMT;
    private javax.swing.JButton BoutonIDE;
    private javax.swing.JButton BoutonRecherchePH;
    private javax.swing.JButton BouttonMT;
    private javax.swing.JButton BouttonMT1;
    private javax.swing.JTable TableIDE;
    private javax.swing.JTable TableMT;
    private javax.swing.JTable TablePH;
    private javax.swing.JTable TableSecretaire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables

}
