/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;


import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;


/**
 *
 * @author Manon
 */
public class ResultatsConsulter extends javax.swing.JPanel {

    public JLabel getType() {
        return type;
    }

    public JTextArea getResultats() {
        return resultats;
    }

    public JButton getBoutonRetour() {
        return boutonRetour;
    }

    public JLabel getIpp() {
        return ipp;
    }

    public JLabel getNomMedecin() {
        return nomMedecin;
    }

    public JLabel getNomPatient() {
        return nomPatient;
    }

    public JLabel getPrenomPatient() {
        return prenomPatient;
    }

 

   
    /**
     * Creates new form PrestationFaite
     */
    public ResultatsConsulter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomPatient = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        prenomPatient = new javax.swing.JLabel();
        ipp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomMedecin = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultats = new javax.swing.JTextArea();
        boutonRetour = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 10, true));

        nomPatient.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        nomPatient.setText("NOM");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/logo.png"))); // NOI18N

        prenomPatient.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        prenomPatient.setText("Prénom");

        ipp.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        ipp.setText("AAMMXXXXX");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel3.setText("Résultats :");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel4.setText("Patient:");

        nomMedecin.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        nomMedecin.setText("Nom Prenom");

        type.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        type.setText("Date de réalisation de la prestation:");

        resultats.setColumns(20);
        resultats.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        resultats.setRows(5);
        jScrollPane2.setViewportView(resultats);

        boutonRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/flcheretour-ConvertImage.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boutonRetour)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomPatient)
                                        .addGap(54, 54, 54)
                                        .addComponent(prenomPatient)
                                        .addGap(74, 74, 74)
                                        .addComponent(ipp)
                                        .addGap(130, 130, 130)
                                        .addComponent(type)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomMedecin)))
                                .addGap(0, 254, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomPatient)
                            .addComponent(prenomPatient)
                            .addComponent(ipp)
                            .addComponent(jLabel4)
                            .addComponent(type)
                            .addComponent(nomMedecin)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boutonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonRetour;
    private javax.swing.JLabel ipp;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nomMedecin;
    private javax.swing.JLabel nomPatient;
    private javax.swing.JLabel prenomPatient;
    private javax.swing.JTextArea resultats;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
